### ISSUE TITLE
Warnings during running PyTorchTOP in MVSC 16.8.3 (Reference Mode)

### ISSUE THREAD

**Issue by vrtx-voiod** [DBraun/PyTorchTOP#6]
I am able to run the solution and the matting works so far, but I get following warnings during running it:

`Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4102	'cv': unreferenced label	PyTorchTOP	*mypath*\src\PyTorchTOP.cpp	470	
Warning	C4005	'NOMINMAX': macro redefinition	PyTorchTOP	*mypath*\src\CPlusPlus_Common.h	26	
Message		see previous definition of 'NOMINMAX'	PyTorchTOP	*mypath*\src\PyTorchTOP.cpp	1	
`

/edit: After aborting and reinitialiszing the Warnings don't occur anymore.

**Comment by DBraun** [comment]
Thanks. I've pushed an update to address these warnings. Visual Studio tends to not show the same warnings over and over unless you clean the build solution. So just because they're not being shown in the error list doesn't mean they've gone away.

**Comment by vrtx-voiod** [comment]
> Thanks. I've pushed an update to address these warnings. Visual Studio tends to not show the same warnings over and over unless you clean the build solution. So just because they're not being shown in the error list doesn't mean they've gone away.

I have used the updated rep you have uploaded and now it works without error messages 👍 

However the issue with the white space in my username as mentioned in [https://github.com/DBraun/PyTorchTOP/issues/5](url) still occurs. I could handle this by manually setting the path in the CMakeList.
